import React from "react";
import { StyleSheet, Dimensions } from "react-native";
import colors from "../../config/colors";
const windowHeight = Dimensions.get("window").height;
const windowWidth = Dimensions.get("window").width;
const tabHeight = 50;
const galleryGridWidth = Math.floor((windowWidth - 20) / 4);
const galleryGridHeight = Math.floor((windowWidth - 20) / 4);
const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#fff",
      },
      body: {
        flex: 9,
      },
      selected: { backgroundColor: "#d3d3d3" },
      list: {},
      icon: {
        position: "absolute",
        bottom: 20,
        width: "100%",
        left: 290,
        zIndex: 1,
      },
      numberBox: {
        position: "absolute",
        bottom: 75,
        width: 30,
        height: 30,
        borderRadius: 15,
        left: 330,
        zIndex: 3,
        backgroundColor: "#e3e3e3",
        justifyContent: "center",
        alignItems: "center",
      },
      number: { fontSize: 14, color: "#000" },
      cardItems: {
        width: windowWidth,
        paddingVertical: 12,
        borderBottomColor: "#e5e5e5",
        borderBottomWidth: 1,
        paddingHorizontal: 10,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
      },placeholder: { fontSize: 17 - 1, marginTop: 15, color: "#7f7f7f" }, //SUBHASH: Change title color here
        wrapper: {
          borderWidth: 1,
          borderColor: "#e5e5e5",
          paddingHorizontal: 10,
          paddingVertical: 10,
          borderRadius: 3,
          width: "100%",
          marginTop: 10,
          flexDirection: "row",
          alignItems: "center",
          justifyContent: "space-between",
        },
        btns: {
          fontSize: 18,
          color: colors.white,
        },
        fieldBox: {
          alignItems: "center",
          width: "100%",
          overflow: "hidden",
          flexDirection: "row",
          padding: 5,
          borderRadius: 3,
          borderColor: "#ddd",
          borderWidth: 1,
          backgroundColor: "#fff",
          height: "auto",
          justifyContent: "space-between",
          marginBottom: 5,
          marginTop: 5,
          shadowColor: "#999",
          shadowOffset: {
          	width: 0,
          	height: 1,
          },
          shadowOpacity: 0.22,
          shadowRadius: 2.22,
          elevation: 3,
        },
        labelName: {
          color: colors.textColor,
          lineHeight: 40,
          fontSize: 14,
          paddingLeft: 4,
          height: "auto",
        },
        textfield: {
          backgroundColor: "#fff",
          height: "auto",
      
          fontSize: 12,
          color: colors.textColor,
          textAlign: "right",
          padding: 5,
        },
        searchBackground: {
                  backgroundColor:colors.primary,
              },
              listItem: {
                  flexDirection: "row",
                  justifyContent: "space-between",
                  paddingVertical: 5,
                  paddingHorizontal: 8,
                  borderWidth: 0.6,
                  borderRadius: 2,
                  borderColor: colors.primary,
                  marginRight: 5,
              },
              name: {
                  fontSize: 14,
                  color: colors.white,
              },
              searchContainer: {
                  backgroundColor: colors.white,
                  flexDirection: 'row',
                  alignItems: 'center',
                  elevation: 5,
                  borderRadius: 3,
                  padding: 5,
                  marginTop: -5,
                  marginBottom: 5,
                  marginHorizontal: 10,
          
              },
              searchField: {
                  width: "90%",
                  marginLeft: 5,
                  color: colors.textColor,
                  fontSize: 18,
              },
              swipesGestureContainer: {
                  width: '100%',
                  backgroundColor: 'red'
              },
              body: {
                        // flex: 9,
                        flexGrow: 1,
                        height: "80%"
                    },
                    content: {
                              padding: 20,
                              height: 100,
                              backgroundColor: '#fff',
                          },
                          active: {
                                    backgroundColor: 'rgba(255,255,255,1)',
                                },
                                inactive: {
                                    backgroundColor: 'rgba(245,252,255,1)',
                                },
                                selectors: {
                                    marginBottom: 10,
                                    flexDirection: 'row',
                                    // justifyContent: 'center',
                                },
                                selector: {
                                    backgroundColor: '#F5FCFF',
                                    padding: 10,
                                },
                                activeSelector: {
                                    fontWeight: 'bold',
                                },
                                selectTitle: {
                                    fontSize: 14,
                                    fontWeight: '500',
                                    padding: 10,
                                },
                                multipleToggle: {
                                    flexDirection: 'row',
                                    justifyContent: 'center',
                                    marginVertical: 30,
                                    alignItems: 'center',
                                },
                                multipleToggle__title: {
                                    fontSize: 16,
                                    marginRight: 8,
                                },
                                selectedItemsContainer: {
                                	width: "100%",
                                	height: "auto",
                                	borderColor: "#ccc",
                                	borderWidth: 1,
                                	backgroundColor: "#f9f6f6",
                                	paddingVertical: 8,
                                	flexDirection: "row",
                                	flexWrap: "wrap",
                                	alignItems: "flex-start",
                                },
                                selectedItemsContainer: {
                                	width: "100%",
                                	flexDirection: "row",
                                	flexWrap: "wrap",
                                	padding:5,
                                }, capsulePress: {
                                          height: 30,
                                          justifyContent: "center",
                                          paddingHorizontal: 3,
                                          paddingVertical: 5,
                                          marginHorizontal: 5,
                                          marginVertical: 5,
                                          borderRadius: 20,
                                          borderWidth: 1,
                                          borderColor: colors.primary,
                                          backgroundColor: colors.primary,
                                      },
                                      capsuleText: {
                                          fontSize: 14,
                                          color: colors.primary,
                                          marginHorizontal: 3,
                                          marginBottom: 2,
                                      },
                                      capsuleTextPress: {
                                          fontSize: 14,
                                          color: colors.white,
                                          marginHorizontal: 3,
                                          marginBottom: 2,
                                      },
                                      icon:{
                                          color: colors.primary ,
                                          fontSize: 20,
                                          marginLeft: 10
                                      },
                                      iconPress:{
                                          color: colors.white ,
                                          fontSize: 20,
                                      },
                                      title: {
                                                textAlign: 'center',
                                                fontSize: 22,
                                                fontWeight: '300',
                                                marginBottom: 20,
                                            },
                                            containerCart: {
                                                  width: "100%",
                                                  paddingVertical: 12,
                                                  borderBottomColor: "#e5e5e5",
                                                  borderBottomWidth: 1,
                                                  paddingHorizontal: 10,
                                                  flexDirection: "row",
                                                  justifyContent: "space-between",
                                                  alignItems: "center",
                                                },
                                                btn: {
                                                  width: 150,
                                                  height: 50,
                                                  justifyContent: "center",
                                                  alignItems: "center",
                                                  borderRadius: 3,
                                                  marginBottom: 5,
                                                  alignSelf: "center",
                                                  marginTop: 20,
                                                },
                                                btnSuccess: {
                                                  backgroundColor: colors.primary,
                                                },
                                                btnText: { color: colors.white, fontSize: 16 },
                                                fieldBox: {
                                                  alignItems: "center",
                                                  width: "100%",
                                                  overflow: "hidden",
                                                  flexDirection: "row",
                                                  padding: 5,
                                                  borderRadius: 3,
                                                  borderColor: "#ddd",
                                                  borderWidth: 1,
                                                  backgroundColor: "#fff",
                                                  height: "auto",
                                                  justifyContent: "space-between",
                                                  marginBottom: 5,
                                                  marginTop: 5,
                                                  shadowColor: "#999",
                                                  shadowOffset: {
                                                  	width: 0,
                                                  	height: 1,
                                                  },
                                                  shadowOpacity: 0.22,
                                                  shadowRadius: 2.22,
                                                  elevation: 3,
                                                },
                                                modalContainer: {
                                                      flex: 1,
                                                      backgroundColor: "#F5FCFF",
                                                      paddingTop: 3,
                                                    },
                                                    wrapper: {
                                                      borderWidth: 1,
                                                      borderColor: "#e5e5e5",
                                                      paddingHorizontal: 10,
                                                      paddingVertical: 10,
                                                      borderRadius: 3,
                                                      width: "100%",
                                                      marginTop: 10,
                                                      flexDirection: "row",
                                                      alignItems: "center",
                                                      justifyContent: "space-between",
                                                    },
                                                    selectWrapper: {
                                                      borderRadius: 10,
                                                      borderWidth: 1,
                                                      height: 90,
                                                      width: 75,
                                                      alignItems: "center",
                                                      justifyContent: "center",
                                                      paddingTop: 5,
                                                      marginLeft: 5,
                                                    },
                                                    img: { resizeMode: "contain", height: 35, width: 35, marginBottom: 5 },
                                                    dateContainer: {
                                                      borderWidth: 1,
                                                      borderRadius: 3,
                                                      paddingVertical: 5,
                                                      marginTop: 5,
                                                      paddingHorizontal: 15,
                                                    },
                                                    daybtn: {
                                                      padding: 5,
                                                      borderRadius: 3,
                                                      height: 45,
                                                      width: 45,
                                                      alignItems: "center",
                                                      justifyContent: "center",
                                                    },
                                                    inputContainer: {
                                                          padding: 10,
                                                        },
                                                        name: {
                                                          fontSize: 18,
                                                          color: colors.textColor,
                                                          marginBottom: 5,
                                                        },
                                                        RadioinputContainer: {
                                                          padding: 10,
                                                          flexDirection: "row",
                                                        },
                                                        Radioname: {
                                                          fontSize: 18,
                                                          color: colors.textColor,
                                                          top: 8,
                                                        },
                                                        inputRadio: {
                                                          marginLeft: 20,
                                                          marginTop: 5,
                                                        },
                                                        inputText: {
                                                          height: 50,
                                                          borderColor: "#ccc",
                                                          borderWidth: 1,
                                                          borderRadius: 3,
                                                          fontSize: 18,
                                                          backgroundColor: "#f9f6f6",
                                                          paddingHorizontal: 10,
                                                          color: colors.textColor,
                                                        },
                                                        title: {
                                                          textAlign: "center",
                                                          fontSize: 22,
                                                          fontWeight: "300",
                                                          marginBottom: 20,
                                                        },
                                                        content: {
                                                          padding: 10,
                                                          height: 200,
                                                          backgroundColor: "#fff",
                                                        },
                                                        capsule: {
                                                              // height: 30,
                                                              // justifyContent: "center",
                                                              justifyContent: "space-between",
                                                              flexDirection: "row",
                                                              paddingHorizontal: 8,
                                                              paddingVertical: 5,
                                                              marginHorizontal: 5,
                                                              marginVertical: 5,
                                                              borderRadius: 3,
                                                              borderWidth: 0.6,
                                                              borderColor: colors.primary,
                                                              backgroundColor: colors.white,
                                                            },
                                                            taskText: {
                                                                  fontSize: 14,
                                                                  flexDirection: "row",
                                                                  color: colors.primary,
                                                                  marginHorizontal: 8,
                                                                  marginTop: 5,
                                                                },
                                                                taskTextPress: {
                                                                  fontSize: 14,
                                                                  flexDirection: "row",
                                                                  color: colors.white,
                                                                  marginHorizontal: 8,
                                                                  marginTop: 5,
                                                                },
                                                                capsuleText: {
                                                                  fontSize: 14,
                                                                  flexDirection: "row",
                                                                  color: colors.primary,
                                                                  marginHorizontal: 3,
                                                                  marginBottom: 2,
                                                                },
                                                                capsuleTextPress: {
                                                                  fontSize: 14,
                                                                  flexDirection: "row",
                                                                  color: colors.white,
                                                                  marginHorizontal: 3,
                                                                  marginBottom: 2,
                                                                },
                                                                btnCover: {
                                                                      width: 100,
                                                                      paddingVertical: 5,
                                                                      backgroundColor: colors.primary,
                                                                      borderRadius: 3,
                                                                      justifyContent: "center",
                                                                      alignItems: "center",
                                                                    },
                                                                    scanModalOverlay: {
                                                                      justifyContent: "center",
                                                                      alignItems: "center",
                                                                      backgroundColor: "rgba(0, 0, 0, 0.8)",
                                                                      width: windowWidth,
                                                                      height: windowHeight,
                                                                    },
                                                                    qrCodeSacnBox: {
                                                                      width: Math.floor((windowWidth * 70) / 100),
                                                                      height: Math.floor((windowWidth * 70) / 100),
                                                                    },
                                                                    cancelButton: {
                                                                      position: "absolute",
                                                                      zIndex: 11,
                                                                      top: 30,
                                                                      left: 10,
                                                                      backgroundColor: colors.lightGrey,
                                                                      width: 30,
                                                                      height: 30,
                                                                      borderRadius: 100,
                                                                      alignItems: "center",
                                                                      justifyContent: "center",
                                                                      elevation: 3,
                                                                    },
                                                                    cancelButtonText: {
                                                                      color: "#000",
                                                                      fontSize: 24,
                                                                    },
                                                                    uncheckedCheckBoxColor: { color: "#7f7f7f" },
                                                                    row: {
                                                                      		flexDirection: "row",
                                                                      		borderBottomColor: "#eee",
                                                                      		borderBottomWidth: 1,
                                                                      		paddingHorizontal: 5,
                                                                      		paddingVertical: 10,
                                                                      	},
  wrapper: {
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 3,
    width: "100%",
    // marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  wrapperForAssign: {
    borderBottomWidth: 1,
    borderColor: "#ddd",
    // paddingHorizontal: 10,
    // paddingVertical: 10,
    borderRadius: 3,
    width: "100%",
    // marginTop: 10,
    // flexDirection: 'row',
    // alignItems: 'center',
    // justifyContent: 'space-between'
  },
  btns: {
    fontSize: Platform.OS === "ios" ? 21 : 18,
    color: colors.white,
  },
  leftPart: {
    		width: "75%",
    		justifyContent: "center",
    	},
    	rightPart: {
    		width: "25%",
    		flexDirection: "row",
    		justifyContent: "flex-end",
    		alignItems: "center",
    	},
      
      fontSize13:{fontSize: 13},
      opacity06:{opacity: 0.6},
      opacity05:{opacity: 0.5},
      borderRadius3:{ borderRadius: 3},
      paddingVertical10:{paddingVertical: 10},
      width150:{ width: 150},

});
export default styles;
