import React from "react";
import * as Localization from "expo-localization";

export default React.createContext({
  userDetails: null,
  groups: [],
  locations: [],
  sections: [],
  categories: [],
  subCategories: [],
  species: [],
  subSpecies: [],
  animals: [],
  selectedAnimalID: undefined,
  animalVaccines: [],
  animalVaccinationDetails: [],
  animalDiagnosis: [],
  animalEnclosures: [],
  animalIncidents: [],
  animalMeasurements: [],
  animalFeedingAssignments: [],
  animalFeedings: [],
  filterDetails: null,
  locale: Localization.locale,
  setLocale: (data) => {},
  setFilterDetails: (data) => {},
  unsetFilterDetails: (data) => {},
  setUserData: (data) => {},
  unsetUserData: () => {},
  setGroups: (data) => {},
  setLocations: (data) => {},
  setSections: (data) => {},
  setCategories: (data) => {},
  setSubCategories: (data) => {},
  setSpecies: (data) => {},
  setSubSpecies: (data) => {},
  setAnimals: (data) => {},
  setAnimalID: (id) => {},
  setAnimalVaccines: (data) => {},
  setAnimalVaccinationDetails: (data) => {},
  setAnimalDiagnosis: (data) => {},
  setAnimalEnclosures: (data) => {},
  setAnimalIncidents: (data) => {},
  setAnimalMeasurements: (data) => {},
  setAnimalFeedingAssignments: (data) => {},
  setAnimalFeedingsData: (data) => {},
});
