// Created by Dibyendu
import { StyleSheet,Dimensions } from "react-native";
import Colors from '../../config/colors'
const windowWidth = Dimensions.get("screen").width;
const windowHeight = Dimensions.get("screen").height;
const tabHeight = 50;
const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 8,
      },
      fieldBox: {
        alignItems: "center",
        width: "100%",
        overflow: "hidden",
        flexDirection: "row",
        padding: 5,
        borderRadius: 3,
        borderColor: "#ddd",
        borderBottomWidth: 1,
        backgroundColor: "#fff",
        height: "auto",
        justifyContent: "space-between",
      },
      labelName: {
        color: Colors.labelColor,
        // lineHeight: 40,
        fontSize: Colors.lableSize,
        paddingLeft: 4,
        height: "auto",
        paddingVertical: 10,
      },
      textfield: {
        backgroundColor: "#fff",
        height: "auto",
    
        fontSize: Colors.textSize,
        color: Colors.textColor,
        textAlign: "left",
        padding: 5,
      },
      addItemRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginVertical: 5,
        paddingHorizontal: 5,
      },
      capsule: {
        height: 25,
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 10,
        paddingBottom: 2,
        borderRadius: 50,
      },
      itemsContainer: {
        marginVertical: 5,
        paddingHorizontal: 5,
      },
      itemRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        paddingVertical: 5,
        borderBottomWidth: 1,
        borderBottomColor: "#eee",
      },
      itemRemoveContainer: {
        width: "10%",
        alignItems: "center",
        justifyContent: "center",
      },
      rowTitleText: {
        fontSize: Colors.headerSize,
        color: Colors.textColor,
        fontWeight: "bold",
        lineHeight: 24,
      },
      rowSubText: {
        color: Colors.textColor,
        opacity: 0.8,
        fontSize: Colors.textSize,
      },
      button: {
        alignItems: "center",
        backgroundColor: Colors.primary,
        padding: 10,
        borderRadius: 20,
        color: "#fff",
        marginVertical: 10,
      },
      textWhite: {
        color: "#fff",
        fontWeight: "bold",
      },
      modalOverlay: {
        justifyContent: "center",
        alignItems: "center",
        width: windowWidth,
        height: windowHeight,
      },
      itemModalContainer: {
        flex: 1,
        width: windowWidth,
        height: windowHeight,
        backgroundColor: Colors.lightGrey,
      },
      itemModalHeader: {
        height: 55,
        flexDirection: "row",
        width: "100%",
        backgroundColor: Colors.primary,
        elevation: 1,
        alignItems: "center",
        justifyContent: "flex-start",
      },
      headerBackBtnContainer: {
        width: "15%",
        height: 55,
        paddingLeft: 8,
        alignItems: "center",
        justifyContent: "center",
      },
      headerTitleContainer: {
        width: "70%",
        paddingLeft: 20,
        height: 55,
        alignItems: "center",
        justifyContent: "center",
      },
      itemModalBody: {
        flex: 1,
        height: windowHeight - 55,
        padding: 8,
      },
      checkBoxRow: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 5,
      },
      checkBoxLabel: {
        marginLeft: 5,
        fontSize: Colors.lableSize,
        color: Colors.textColor,
      },
      errorFieldBox: {
        borderWidth: 1,
        borderColor: Colors.tomato,
      },

      radioField: {
            flexDirection: "row",
            alignItems: "center",
            marginHorizontal: 5,
          },
          radioText: {
            marginLeft: 8,
            fontSize: Colors.textSize,
            color: Colors.textColor,
          },
          imageHeight:{ height: 30, width: 30},
          imagePicker: {
                borderColor: "#ccc",
                borderWidth: 1,
                padding: 3,
                backgroundColor: "#fff",
                borderRadius: 3,
                alignItems: "center",
                justifyContent: "center",
              },
              radioButton: {
                    flexDirection: "row",
                    padding: 3,
                  },
                  radioButtonLabel: {
                    fontSize: Colors.textSize,
                    color: Colors.textColor,
                    marginLeft: 5,
                  },
                  addItemRow: {
                    		flexDirection: "row",
                    		justifyContent: "space-between",
                    		alignItems: "center",
                    		marginVertical: 5,
                    		paddingHorizontal: 5,
                    	},
                    	capsule: {
                    		height: 25,
                    		flexDirection: "row",
                    		alignItems: "center",
                    		paddingHorizontal: 10,
                    		paddingBottom: 2,
                    		borderRadius: 50,
                    	},
                    	itemsContainer: {
                    		marginVertical: 5,
                    		paddingHorizontal: 5,
                    		borderRadius: 3,
                    	},
                    	itemRow: {
                    		paddingVertical: 5,
                    		borderBottomWidth: 1,
                    		borderBottomColor: "#eee",
                    	},
                    	itemRowHeading: {
                    		flexDirection: "row",
                    		justifyContent: "space-between",
                    		alignItems: "center",
                    	},
                    	itemRowBody: {
                    		flexDirection: "row",
                    		justifyContent: "space-between",
                    		alignItems: "center",
                    		paddingRight: 10,
                    	},
                    	rowTitleText: {
                    		fontSize: Colors.textSize,
                    		color: Colors.textColor,
                    		fontWeight: "bold",
                    		lineHeight: 24,
                    	},
                    	rowSubText: {
                    		color: Colors.textColor,
                    		opacity: 0.8,
                    		fontSize: Colors.textSize,
                    	},
                    	totalRow: {
                    		paddingVertical: 5,
                    		borderBottomWidth: 1,
                    		borderColor: "#eee",
                    		flexDirection: "row",
                    		alignItems: "center",
                    		justifyContent: "space-between",
                    	},
                      fieldBox: {
                        		alignItems: "center",
                        		width: "100%",
                        		overflow: "hidden",
                        		flexDirection: "row",
                        		padding: 5,
                        		borderRadius: 3,
                        		borderColor: "#ddd",
                        		borderBottomWidth: 1,
                        		backgroundColor: "#fff",
                        		height: "auto",
                        		justifyContent: "space-between",
                        		shadowColor: "#999",
                        		shadowOffset: {
                        			width: 0,
                        			height: 1,
                        		},
                        		shadowOpacity: 0.22,
                        		shadowRadius: 2.22,
                        		elevation: 3,
                        	},
                        	fieldBox2: {
                        		alignItems: "center",
                        		width: "100%",
                        		overflow: "hidden",
                        		flexDirection: "row",
                        		padding: 5,
                        		borderRadius: 3,
                        		borderColor: "#ddd",
                        		borderBottomWidth: 1,
                        		backgroundColor: "#fff",
                        		height: "auto",
                        		justifyContent: "space-between",
                        		shadowColor: "#999",
                        		shadowOffset: {
                        			width: 0,
                        			height: 1,
                        		},
                        		shadowOpacity: 0.22,
                        		shadowRadius: 2.22,
                        		elevation: 3,
                        	},
                        	labelName: {
                        		color: Colors.labelColor,
                        		 lineHeight: 40,
                        		fontSize: Colors.lableSize,
                        		paddingLeft: 4,
                        		height: "auto",
                        		paddingVertical: 10,
                        	},
                        	textfield: {
                        		backgroundColor: "#fff",
                        		height: "auto",
                          
                        		fontSize: Colors.textSize,
                        		color: Colors.textColor,
                        		textAlign: "left",
                        		padding: 5,
                        	},
                        	descfield: {
                        		backgroundColor: "#fff",
                            
                        		fontSize: Colors.textSize,
                        		color: Colors.textColor,
                        		textAlign: "right",
                        		width: "50%",
                        		padding: 5,
                        	},
                          row: {
                            		flexDirection: "row",
                            		borderBottomColor: "#eee",
                            		borderBottomWidth: 1,
                            		paddingHorizontal: 5,
                            		paddingVertical: 5,
                            	},
                            	leftPart: {
                            		width: "75%",
                            		justifyContent: "center",
                            	},
                            	rightPart: {
                            		width: "25%",
                            		flexDirection: "row",
                            		justifyContent: "flex-end",
                            		alignItems: "center",
                            	},
                            	name: {
                            		fontSize: 16,
                            		color: Colors.textColor,
                            		fontWeight: "bold",
                            		lineHeight: 24,
                            	},
                            	subText: {
                            		color: Colors.textColor,
                            		opacity: 0.8,
                            		fontSize: 14,
                            		lineHeight: 22,
                            	},
                            	qtyBox: {
                            		backgroundColor: Colors.primary,
                            		paddingHorizontal: 5,
                            		paddingVertical: 3,
                            		borderRadius: 3,
                            	},
                            	qtyText: {
                            		fontSize: 14,
                            		color: "#FFF",
                            	},
                            	iconStyle: {
                            		fontSize: 18,
                            		color: "#cecece",
                            	},
                              	
titleText: {
		fontSize: 14,
		color: Colors.textColor,
		fontWeight: "bold",
	},
	subText: {
		color: Colors.textColor,
		opacity: 0.8,
		fontSize: 14,
		lineHeight: 22,
	},
	itemInfoContainer: {
		height: 120,
		padding: 15,
		borderBottomWidth: 1,
		borderBottomColor: "#eee",
	},
	pendingStatus: {
		color: Colors.warning,
	},
	approveStatus: {
		color: Colors.primary,
	},
	rejectStatus: {
		color: Colors.danger,
	},
	theadRow: {
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 8,
		paddingVertical: 15,
		backgroundColor: Colors.lightGrey,
		borderBottomColor: "#ddd",
		borderBottomWidth: 1,
	},
	tbodyRow: {
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 5,
		paddingVertical: 15,
		borderBottomColor: "#ddd",
		borderBottomWidth: 1,
	},
	firstCol: {
		flex: 1,
		flexDirection: "row",
		alignItems: "center",
	},
	checkboxContainer: {
		width: 25,
		height: 25,
		alignItems: "center",
		justifyContent: "center",
	},
	btnContainer: {
		height: 60,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 8,
	},
	approveBtn: {
		width: 150,
		height: 50,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: Colors.primary,
		borderRadius: 4,
	},
	rejectBtn: {
		width: 150,
		height: 50,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: Colors.tomato,
		borderRadius: 4,
	},
	btnText: {
		fontSize: 14,
		color: "#fff",
		fontWeight: "bold",
	},
	modalOverlay: {
		justifyContent: "center",
		alignItems: "center",
		width: windowWidth,
		height: windowHeight,
	},
	itemModalContainer: {
		flex: 1,
		width: windowWidth,
		height: windowHeight,
		backgroundColor: Colors.lightGrey,
	},
	itemModalHeader: {
		height: 55,
		flexDirection: "row",
		width: "100%",
		backgroundColor: Colors.primary,
		elevation: 1,
		alignItems: "center",
		justifyContent: "flex-start",
	},
	labelName: {
		color: Colors.textColor,
		lineHeight: 40,
		fontSize: 14,
		paddingLeft: 4,
	},
	textfield: {
		backgroundColor: "#fff",
		height: 40,
		
		fontSize: 12,
		color: Colors.textColor,
		textAlign: "right",
		width: "60%",
		padding: 5,
	},
  tab: {
    		flex: 1,
    		alignItems: "center",
    		justifyContent: "center",
    		height: tabHeight,
    	},
    	underlineStyle: {
    		backgroundColor: Colors.primary,
    		height: 3,
    	},
    	activeTab: {
    		height: tabHeight - 1,
    		borderBottomWidth: 2,
    		borderBottomColor: Colors.primary,
    	},
    	activeText: {
    		fontSize: 14,
    		fontWeight: "bold",
    		color: Colors.primary,
    	},
    	inActiveText: {
    		fontSize: 14,
    		color: Colors.textColor,
    		opacity: 0.8,
    	},
    	listContainer: {
    		flex: 1,
    		padding: 8,
    		height: windowHeight - tabHeight,
    	},
    	CardBox: {
    		padding: 5,
    		borderRadius: 3,
    		borderColor: "#ddd",
    		borderWidth: 1,
    		backgroundColor: "#fff",
    		justifyContent: "space-between",
    		marginBottom: 5,
    		marginTop: 5,
    		// shadowColor: "#999",
    		// shadowOffset: {
    		// 	width: 0,
    		// 	height: 1,
    		// },
    		// shadowOpacity: 0.22,
    		// shadowRadius: 2.22,
    		// elevation: 3,
    	},
    	labelName: {
    		fontSize: 12,
    		paddingLeft: 4,
        
    		color: Colors.textColor,
    		opacity: 0.9,
    		textAlign: "left",
    		fontWeight: "bold",
    		flex: 1,
    		width: "100%",
    	},
    	mc: {
    		color: Colors.textColor,
    		opacity: 0.8,
    		marginLeft: 5,
    		fontSize: 12,
    		fontWeight: "500",
    	},
    	pendingStatus: {
    		textAlign: "right",
    		color: Colors.warning,
    		fontStyle: "italic",
    	},
    	approveStatus: {
    		textAlign: "right",
    		color: Colors.success,
    		fontStyle: "italic",
    	},
    	rejectStatus: {
    		textAlign: "right",
    		color: Colors.danger,
    		fontStyle: "italic",
    	},	tabContainer: {
        		width: "100%",
        		height: tabHeight,
        		flexDirection: "row",
        		borderBottomWidth: 1,
        		borderBottomColor: "#d1d1d1",
        		borderTopWidth: 1,
        		borderTopColor: Colors.primary,
        		elevation: 1,
        	},
          pl12: {
            		paddingLeft: 12,
            	},
            	btn: {
            		// width: Math.floor(windowWidth / 2),
            		paddingVertical: 20,
            		flexDirection: "row",
            		alignItems: "center",
            	},
            	imgContainer: {
            		width: "20%",
            	},
            
            	title: {
            		width: "72%",
            		fontSize: 16,
            		color: Colors.textColor,
            		fontWeight: "bold",
            	},
              saveBtn: {
                		alignItems: "center",
                		backgroundColor: Colors.primary,
                		padding: 10,
                		shadowColor: "#000",
                		shadowOffset: {
                			width: 0,
                			height: 2,
                		},
                		shadowOpacity: 0.23,
                		shadowRadius: 2.62,
                		elevation: 4,
                		borderRadius: 20,
                		color: "#fff",
                		marginVertical: 10,
                	},
                	saveBtnText: {
                		fontSize: Colors.textSize,
                		color: "#fff",
                		fontWeight: "bold",
                	},
                	errorFieldBox: {
                		borderWidth: 1,
                		borderColor: Colors.tomato,
                	},
                  modalOverlay: {
                    		justifyContent: "center",
                    		alignItems: "center",
                    		width: windowWidth,
                    		height: windowHeight,
                    	},
                    	stockModalContainer: {
                    		flex: 1,
                    		width: windowWidth,
                    		height: windowHeight,
                    		backgroundColor: Colors.lightGrey,
                    	},
                    	stockModalHeader: {
                    		height: 55,
                    		flexDirection: "row",
                    		width: "100%",
                    		backgroundColor: Colors.primary,
                    		elevation: 1,
                    		alignItems: "center",
                    		justifyContent: "flex-start",
                    	},
                    	headerBackBtnContainer: {
                    		width: "15%",
                    		height: 55,
                    		paddingLeft: 8,
                    		alignItems: "center",
                    		justifyContent: "center",
                    	},
                    	headerTitleContainer: {
                    		width: "70%",
                    		paddingLeft: 20,
                    		height: 55,
                    		alignItems: "center",
                    		justifyContent: "center",
                    	},
                    	stockModalBody: {
                    		flex: 1,
                    		height: windowHeight - 55,
                    		padding: 8,
                    	},
                    	fieldBox: {
                    		alignItems: "center",
                    		width: "100%",
                    		overflow: "hidden",
                    		flexDirection: "row",
                    		padding: 5,
                    		borderRadius: 3,
                    		borderColor: "#ddd",
                    		borderBottomWidth: 1,
                    		backgroundColor: "#fff",
                    		height: "auto",
                    		justifyContent: "space-between",
                    	},
                    	labelName: {
                    		color: Colors.labelColor,
                    		// lineHeight: 40,
                    		fontSize: Colors.lableSize,
                    		paddingLeft: 4,
                    		height: "auto",
                    		paddingVertical: 10,
                    	},
                    	textfield: {
                    		backgroundColor: "#fff",
                    		height: "auto",
                    		width: '60%',
                    		fontSize: Colors.textSize,
                    		color: Colors.textColor,
                    		textAlign: "left",
                    		padding: 5,
                    	},
                      itemInfoContainer: {
                        		padding: 15,
                        		borderBottomWidth: 1,
                        		borderBottomColor: "#eee",
                        	},
                        	scrollableTab: {
                        		marginTop: 10,
                        		backgroundColor: Colors.white,
                        		borderColor: "#FFF",
                        	},
                        	underlineStyle: {
                        		backgroundColor: Colors.primary,
                        		height: 3,
                        	},
                        	activeTab: {
                        		backgroundColor: Colors.white,
                        		paddingVertical: 3,
                        	},
                        	activeText: {
                        		fontSize: Colors.textSize,
                        		fontWeight: "bold",
                        		color: Colors.primary,
                        	},
                        	inActiveTab: {
                        		backgroundColor: Colors.white,
                        		paddingVertical: 3,
                        	},
                        	inActiveText: {
                        		fontSize: Colors.textSize,
                        		color: Colors.textColor,
                        		opacity: 0.8,
                        	},
                        	imagePicker: {
                        		width: 50,
                        		height: 50,
                        		marginTop: 5,
                        		borderColor: "#ccc",
                        		borderWidth: 1,
                        		padding: 3,
                        		backgroundColor: "#fff",
                        		borderRadius: 3,
                        		alignItems: "center",
                        		justifyContent: "center",
                        	},
                          headingText: {
                            		fontSize: Colors.lableSize,
                            		color: Colors.textColor,
                            		fontWeight: "bold",
                            	},
                              itemTitleContainer: {
                                		paddingVertical: 12,
                                		paddingHorizontal: 5,
                                		borderBottomWidth: 1,
                                		borderBottomColor: "#eee",
                                	},
                                  searchModalOverlay: {
                                    		justifyContent: "center",
                                    		alignItems: "center",
                                    		backgroundColor: Colors.white,
                                    		width: windowWidth,
                                    		height: windowHeight,
                                    	},
                                    	seacrhModalContainer: {
                                    		flex: 1,
                                    		backgroundColor: Colors.white,
                                    		width: windowWidth,
                                    		height: windowHeight,
                                    		elevation: 5,
                                    	},
                                    	searchModalHeader: {
                                    		height: 55,
                                    		width: "100%",
                                    		elevation: 5,
                                    		paddingHorizontal: 10,
                                    		flexDirection: "row",
                                    		alignItems: "center",
                                    		justifyContent: "flex-start",
                                    		backgroundColor: Colors.primary,
                                    	},
                                    	searchBackBtn: {
                                    		width: "10%",
                                    		height: 55,
                                    		alignItems: "flex-start",
                                    		justifyContent: "center",
                                    	},
                                    	searchContainer: {
                                    		width: "90%",
                                    		flexDirection: "row",
                                    		alignItems: "flex-start",
                                    		justifyContent: "center",
                                    	},
                                    	searchFieldBox: {
                                    		width: "100%",
                                    		height: 40,
                                    		paddingHorizontal: 10,
                                    		flexDirection: "row",
                                    		alignItems: "center",
                                    		justifyContent: "space-between",
                                    		backgroundColor: "rgba(0,0,0, 0.1)",
                                    		borderRadius: 50,
                                    	},
                                    	searchField: {
                                    		width: "90%",
                                    		padding: 5,
                                    		color: Colors.white,
                                    		fontSize: 15,
                                    	},
                                    	searchModalBody: {
                                    		flex: 1,
                                        height: windowHeight - 55,
                                      },
                                      modalContainer: {
                                        		flex: 1,
                                        		justifyContent: "center",
                                        		alignItems: "center",
                                        		backgroundColor: "rgba(0, 0, 0, 0.5)",
                                        	},
                                        	closerBtn: {
                                        		top:20,
                                        		bottom: 10,
                                        		padding: 10
                                        	},
                                        	closeBtnText: {
                                        		fontSize: 16,
                                        		fontWeight: "bold",
                                        		color: Colors.tomato,
                                        	},
                                        	modalBody: {
                                        		alignItems: "center",
                                        		justifyContent: "center",
                                        		backgroundColor: Colors.white,
                                        		width: Math.floor((windowWidth * 60) / 100),
                                        		minHeight: Math.floor(windowHeight / 5),
                                        		padding: 15,
                                        		borderRadius: 3,
                                        		elevation: 5,
                                        	},
                                        	downloadBtn: {
                                        		flexDirection: "row",
                                        		paddingHorizontal: 20,
                                        		paddingVertical: 8,
                                        		borderWidth: StyleSheet.hairlineWidth,
                                        		borderRadius: 3,
                                        	},
                                          input: {
                                            		height: 40,
                                            		margin: 12,
                                            		borderWidth: 1,
                                            		padding: 10,
                                            		borderColor: Colors.mediumGrey
                                            	},
                                            	btn: {
                                            		width: 100,
                                            		height: 30,
                                            		justifyContent: 'center',
                                            		alignItems: 'center',
                                            		borderRadius: 3,
                                            		marginBottom: 5
                                            	},
                                            	btnExtra: {
                                            		width: 130,
                                            		height: 50,
                                            		justifyContent: 'center',
                                            		alignItems: 'center',
                                            		borderRadius: 3,
                                            		marginBottom: 5
                                            	},
                                            	btnDanger: {
                                            		backgroundColor: Colors.danger,
                                            	},
                                            	btnSuccess: {
                                            		backgroundColor: Colors.success,
                                            	},
                                            	btnText: { color: Colors.white },
                                            	searchModalOverlay: {
                                            		justifyContent: "center",
                                            		alignItems: "center",
                                            		backgroundColor: Colors.white,
                                            		width: windowWidth,
                                            		height: windowHeight,
                                            	},
                                            	seacrhModalContainer: {
                                            		flex: 1,
                                            		backgroundColor: Colors.white,
                                            		width: windowWidth,
                                            		height: windowHeight,
                                            		elevation: 5,
                                            	},
                                            	searchModalHeader: {
                                            		height: 55,
                                            		width: "100%",
                                            		elevation: 5,
                                            		paddingHorizontal: 10,
                                            		flexDirection: "row",
                                            		alignItems: "center",
                                            		justifyContent: "flex-start",
                                            		backgroundColor: Colors.primary,
                                            	},
                                              //Modal Style
	textStyle: {
		color: "white",
		fontWeight: "bold",
		textAlign: "center"
	},
	modalText: {
		marginBottom: 15,
		textAlign: "center"
	},
	detailText: {
		textAlign: "center"
	},
	detailsContainer: {
		marginBottom: 8
	},
	centeredView: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		marginTop: 22
	},
	modalView: {
		margin: 20,
		backgroundColor: "white",
		borderRadius: 20,
		padding: 35,
		alignItems: "center",
		// shadowColor: "#000",
		// shadowOffset: {
		// 	width: 0,
		// 	height: 2
		// },
		// shadowOpacity: 0.25,
		// shadowRadius: 4,
		// elevation: 5
	},
  rightPart: {
    		width: "25%",
    		justifyContent: "center",
    	},
    	rightPartStock: {
    		flexDirection: 'row',
    		justifyContent: 'space-between',
    		alignItems: 'center',
    		flex: 1 / 2
    	},
    	rightPartButton: {
    		padding: 5,
    		alignItems: 'center',
    		backgroundColor: Colors.primary,
    		borderRadius: 3
    	},
    	rightPartButtonText: {
    		color: Colors.white
    	},
    })
export default styles;